# Generated by Django 5.2.4 on 2025-07-20 21:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#007bff",
                        help_text="Hex color code for UI display",
                        max_length=7,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Operation Category",
                "verbose_name_plural": "Operation Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaperSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "width_cm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "is_standard",
                    models.BooleanField(
                        default=False, help_text="Standard industry size (A4, A3, etc.)"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaperType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "weight_gsm",
                    models.PositiveIntegerField(
                        help_text="Weight in grams per square meter"
                    ),
                ),
                (
                    "price_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per kilogram",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PrintingMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "max_paper_width_cm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_paper_height_cm",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("max_colors", models.PositiveIntegerField(default=4)),
                (
                    "cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Operating cost per hour",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("per_piece", "Per Piece"),
                            ("per_weight", "Per Weight (kg)"),
                            ("per_sheet", "Per Sheet"),
                            ("per_color", "Per Color"),
                            ("outsourcing", "Outsourcing (Fixed Rate)"),
                            ("custom", "Custom Formula"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "makeready_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed setup cost",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per piece/kg/sheet/color",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "outsourcing_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed outsourcing rate",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "makeready_time_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Setup time in minutes"
                    ),
                ),
                (
                    "time_per_unit_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Processing time per unit in seconds"
                    ),
                ),
                (
                    "divides_quantity_by",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Divide current quantity by this number (for cutting operations)",
                    ),
                ),
                (
                    "multiplies_quantity_by",
                    models.PositiveIntegerField(
                        default=1, help_text="Multiply current quantity by this number"
                    ),
                ),
                (
                    "custom_cost_formula",
                    models.TextField(
                        blank=True,
                        help_text="Python expression for custom cost calculation",
                    ),
                ),
                (
                    "custom_time_formula",
                    models.TextField(
                        blank=True,
                        help_text="Python expression for custom time calculation",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_colors",
                    models.BooleanField(
                        default=False,
                        help_text="Operation cost depends on number of colors",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="operations.operationcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__sort_order", "name"],
                "unique_together": {("name", "category")},
            },
        ),
    ]
