# Generated by Django 5.2.4 on 2025-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_operation_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('waiting_manager', 'Waiting Manager Approval / Review'), ('waiting_client', 'Waiting for Client Approval'), ('approved', 'Approved Orders'), ('urgent', 'Urgent Orders'), ('finished', 'Finished Order'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
