# Generated by Django 5.2.4 on 2025-07-29 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_status'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Job completion deadline', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='paper_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of paper', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='parts_of_selling_size',
            field=models.PositiveIntegerField(default=1, help_text='How many printing sheets fit in one parent sheet'),
        ),
        migrations.AlterField(
            model_name='job',
            name='selling_size',
            field=models.ForeignKey(help_text='Parent sheet size that paper is purchased in', on_delete=django.db.models.deletion.PROTECT, related_name='jobs_selling_size', to='operations.papersize'),
        ),
        migrations.AlterField(
            model_name='job',
            name='sheets_to_buy',
            field=models.PositiveIntegerField(blank=True, help_text='Total parent sheets to purchase', null=True),
        ),
    ]
