# Generated by Django 5.2.4 on 2025-07-29 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_deadline_job_paper_cost_and_more'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='custom_end_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom end size height in cm', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_end_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom end size width in cm', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_size',
            field=models.ForeignKey(blank=True, help_text='Final product size', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_end_size', to='operations.papersize'),
        ),
    ]
