# Generated by Django 5.2.4 on 2025-07-29 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_custom_end_height_job_custom_end_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total job cost (sum of all costs)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
