# Generated by Django 5.2.4 on 2025-07-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_update_export_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpdfexport',
            name='export_type',
            field=models.CharField(choices=[('estimate', 'Estimate/Quote'), ('job_sheet', 'Job Sheet')], max_length=20),
        ),
    ]
