# Generated by Django 5.2.4 on 2025-08-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_alter_jobpdfexport_export_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobvariant",
            name="operations_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Operations cost for this quantity",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="jobvariant",
            name="paper_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Paper cost for this quantity",
                max_digits=12,
            ),
        ),
    ]
